logo: IMG-20181230-WA0003~2_1.jpg
title: Nagesh Dewangan
description: Condition Monitoring Engineer
googlescholar: https://scholar.google.com/citations?user=PmYCO64AAAAJ&hl=en
github: "NageshDewangan"
#orcid: "http://orcid.org/yourorcidurl"
researchgate: https://www.researchgate.net/profile/Nagesh-Dewangan-2
email: nagesh@iitkgp.ac.in
show_downloads: true
theme: jekyll-theme-minimal
