title: Nagesh Dewangan
#logo: (https://github.com/NageshDewangan/NageshDewangan.github.io/assets/148441065/f7a641eb-e621-412b-9a82-beb51136cea9)
discription: Maintenance Engineer
show_downloads: false
theme: jekyll-theme-minimal
